image:
  file: .gitpod/Dockerfile
tasks:
   - before: mkdir bazel-cache && rm ~/.cache -rf && ln -s $(readlink -f bazel-cache) $HOME/.cache
   - prebuild: ls $HOME/ -lh && echo "ABC" > $HOME/.cache/ABC && ls -lh 
#  - prebuild: cd dashboard/client && npm install && npm run build && cd - && bazel build //:ray_pkg --jobs=4
github:
  prebuilds:
    master: false
    branches: true
