image:
  file: .gitpod/Dockerfile
tasks:
   - before: export PIP_CACHE_DIR=/workspace/ray/.pip-cache
     prebuild: cd dashboard/client && npm install && npm run build && cd - && bazel build //:ray_pkg --jobs=4 && cd python && pip install -e . && cd ../
github:
  prebuilds:
    master: false
    branches: true
