image:
  file: .gitpod/Dockerfile
tasks:
  - prebuild: cd dashboard/client && npm install && npm run build && cd - && bazel build //:gcs_actor_manager_test
    #bazel build //:ray_pkg --jobs=4 && cd python && SKIP_THIRDPARTY_INSTALL=1 pip install -e .
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false
    # enable for all branches in this repo (defaults to false)
    branches: true
