base_image: "anyscale/ray-ml:pinned-nightly-py37"
env_vars: {"RAY_grpc_based_resource_broadcast": "true"}
debian_packages: ["pssh"]

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  # - pip uninstall -y ray
  # - pip3 install ray[all]@https://ray-wheels.s3.us-west-2.amazonaws.com/upstream/test_wheels/grpc-broadcast/5da79856b0b2d28bcdccab27a3f4519decd4fea8/ray-2.0.0.dev0%2Bdbg-cp37-cp37m-manylinux2014_x86_64.whl
  - pip3 install sklearn
