load("@capnp-cpp//src/capnp:cc_capnp_library.bzl", "cc_capnp_library")

cc_capnp_library(
    name = "ray_capnp",
    srcs = [
        "ray_task.capnp",
        "ray_runtime_env.capnp",
    ],
    visibility = ["//visibility:public"],
)
