cloud_id: {{env["ANYSCALE_CLOUD_ID"]}}

region: us-west-2
aws:
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: true
            VolumeSize: 30

head_node_type:
    name: head_node
    instance_type: m5.16xlarge

worker_node_types:
   - name: worker_node
     instance_type: m5.2xlarge
     min_workers: 500
     max_workers: 500
     use_spot: false
