cloud_id: cld_41THJUKS3PBYvwIynRggIb
region: us-west-2

min_workers: 1000

aws:
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 500

head_node_type:
    name: head_node
    instance_type: m4.16xlarge
    resources:
      cpu: 64

worker_node_typesnn:
   - name: worker_node
     instance_type: m4.large
     min_workers: 1000
     max_workers: 1000
     use_spot: false
     resources:
      cpu: 2
