cloud_id: cld_4F7k8814aZzGG8TNUGPKnc

region: us-west-2

aws:
    BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 500

head_node_type:
    name: head_node
    instance_type: m4.16xlarge
    resources:
      cpu: 64

worker_node_types:
   - name: worker_node
     instance_type: m4.large
     max_workers: 500
     use_spot: false
     resources:
      cpu: 2
